name: release

on:
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  release:
    runs-on: snowbridge-runner
    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('parachain/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - uses: ./.github/actions/install_toolchain
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path parachain/Cargo.toml --workspace --release
      - uses: actions/upload-artifact@v1
        with:
          name: snowbridge-node
          path: parachain/target/release/snowbridge
